# Site settings
title: Nick Freear’s blog
email: nfreear+@+yahoo.co.uk
description: Accessibility, e-learning, internationalization, web dev, Moodle and other stuff
ex_long_desc: > # this means to ignore newlines until "baseurl:"
  This is an experiment!
  I’m rebooting my blog using GitHub pages & Jekyll.
  <a href="https://github.com/nfreear/nfreear.github.io">(site source)</a>
  <br>
  The blog archive is at <a href="https://freear.org.uk">Freear.org.uk</a> &bull; &copy;Nick Freear.

  <i>
  <a href="https://nfreear.mit-license.org/2009-2020#!-blog"><img alt="MIT license"
  src="/assets/shields-io-license-MIT.svg"
  data-src="https://img.shields.io/badge/license-MIT-blue.svg" title=
  "Code: source code snippets are released under an MIT license"></a>

  <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/"
  ><img alt="Creative Commons License"
  src="/assets/license-cc-by-sa-88x31.png" data-src="https://licensebuttons.net/l/by-sa/4.0/88x31.png" title=
  "Content: released under a Creative Commons Attribution-ShareAlike 4.0 License"></a>
  </i>
excerpt_separator: "<!--more-->"
#paginate: 2
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nick.freear.org.uk"
#url: "http://nfreear.github.io" # the base hostname & protocol for your site
twitter_username: nfreear
github_username:  nfreear

x-github-url: https://github.com/nfreear/nfreear.github.io

# Site setting extensions.

# 'truncatewords: 28' (Was: truncate: 220)
ex_excerpt_truncate: 28
ex_comments: false
ex_bodyclass: tribute

x_csp_site_enable: false
# x_black_ribbon: My thoughts are with the victims of the Manchester attack, 22 May 2017.

js_config:
  # Google Analytics.
  analytics_id: UA-8330079-6
  # comment_acct was: "7a9708780eedbfa6976e905b93424255"
  comment_via: IntenseDebate
  comment_acct: "e7e6973336bc863b96ed224779c2629c"
  comment_div: comments  # Was: x-idc-comments-wrap;
  #js_local: 1


# https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#standard-filters [ "%b %-d, %Y"  ]
date_format: "%-d %B %Y"

ex_feed_limit: 100  # Default: 10;

ex_custom_nav:
  - <a href="https://freear.org.uk/moodle/" title="Moodle 2 for Teaching 4-9 Year Olds Beginner's Guide, by Nick Freear">Moodle book</a>
  - <a href="https://accessify.wikia.com/wiki/Accessify_Wiki" title="Working together to fix accessibility on the Web, one site at a time">Accessify Wiki</a>
  - <a href="https://freear.org.uk/" title="My legacy blog, Freear.org.uk">Legacy</a>
  #- <a href="#">Test 2</a>

#ex_site_message: Hello world! Just a <a href="#">test</a>!
__ex_site_message: >
  Help us fund features – vote for Open Media Player! &nbsp;
  <a href="https://elevator.jisc.ac.uk/e/accessiblebydesign/idea/open-media-player"
  ><img src="https://img.shields.io/badge/Jisc-vote_%E2%9C%93-ff6d00.svg"
  alt="Vote! Jisc" title="Vote for us in the Jisc Accessible by Design challenge" /></a>

# https://access.ecs.soton.ac.uk/ToolBar/
# https://atbar.org/
ex_atbar: true

exclude:
  #- _drafts/do-not-delete.txt
  - Makefile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - package-lock.json
  - ".htaccess"
  - LICENSE.MD
  - README.md
  - index.php
  - _posts/_blog.md
  - _out/
  - _bin/
  - node_modules/
  - vendor
  #- package.json

include:
  - _pages

# https://wiki.mozilla.org/Security/Guidelines/Web_Security
webrick:
  headers:
    X-NDF: 1
    # C-S-P-: ... ?!
    X-Content-Type-Options: nosniff
    X-Frame-Options: sameorigin
    X-XSS-Protection: 1
    # Error?? Referrer-Policy: same-origin
    Content-Language: en
    Content-Script-Type: text/javascript; charset=utf-8

# Build settings
markdown: kramdown

egg: Unccl oveguqnl gb lbh!

# End.
